FROM coutinho57/oracle_meta

# RUN source /home/oracle/.bashrc; sqlplus /nolog

# RUN connect sys/Oradoc_db1 as sysdba; \
#     alter session set "_ORACLE_SCRIPT"=true; \
#     create user develop identified by develop; \
#     GRANT ALL PRIVILEGES TO develop;